version: '3'

services:
  console:
    build:
      dockerfile: docker/dev/Dockerfile
      args:
        - CURRENT_UID=${CURRENT_UID}
        - CURRENT_USERNAME=${CURRENT_USERNAME}
    user: ${CURRENT_UID}:${CURRENT_GID}
    environment:
      - CURRENT_USERNAME=${CURRENT_USERNAME}
